
server:
  port: 8081


spring:
  datasource:
    name: ${SQLNAME}
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
#    separator: $$$


clickhouse:
  ip: 192.168.174.128
  httpUrl: http://${clickhouse.ip}:8123
  datasource:
    jdbcUrl: jdbc:clickhouse://${clickhouse.ip}:8123?tcp_keep_alive=true
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
    minimumIdle: 10
    maximumPoolSize: 100
    idleTimeout: 30000
    maxLifetime: 600000





## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


