mybatisGenerator:
  datasource:
    type: mysql
    address: localhost:3306
    db: test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  targetPackage:
    model: com.example.demo.model
    mapper: com.example.demo.mapper
    javaXmlFilesSamePackage: true

  targetRuntime: MyBatis3DynamicSql
  mapperSuffixName: mapper
  java8: false
  disableExample: true

  plugins:
    comment: true
    lombok: false
    swagger: false
    mapperAnnotation: false
    serializable: false

  tables:
    - user
